### ISSUE TITLE
Loading transparent images does not work properly

### ISSUE THREAD

**Issue by subsoap** [ImmutableOctet/mojo2_async_loaders-monkey#1]
When attempting to load a PNG with a transparent background the transparent background is full solid white instead.

From reading the source and comparing it to normal mojo2 image loading, not sure what's wrong.

**Comment by subsoap** [comment]
![test](https://cloud.githubusercontent.com/assets/409170/23205568/3273aab6-f89f-11e6-82d9-9002b61835b2.png)
Test image attached for testing.

**Comment by ImmutableOctet** [comment]
Fixed as of commit e05456333233cb53d08bc9a4320f23a90280fd4c. Pull the [latest version](https://github.com/ImmutableOctet/mojo2_async_loaders-monkey/archive/master.zip) in order to apply the fix.
